{{ if .Values.acmeClusterIssuer.enabled }}
{{ if eq .Values.acmeClusterIssuer.adminEmailAddress "" }}
  {{ fail "adminEmailAddress must be provided when enabling the issuer template" }}
{{ end }}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  namespace: {{ .Release.Namespace | quote }}
  name: acme
  labels:
    {{- include "shipmight.commonLabels" . | nindent 4 }}
    cert-manager-issuer.shipmight.com/id: acme
  annotations:
    cert-manager-issuer.shipmight.com/name: {{ .Values.acmeClusterIssuer.name | quote }}
spec:
  acme:
    email: {{ .Values.acmeClusterIssuer.adminEmailAddress | quote }}
    server: {{ .Values.acmeClusterIssuer.server | quote }}
    privateKeySecretRef:
      name: acme-account-key
    solvers:
    - http01:
        ingress:
          class: nginx
{{ end }}
