---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace | quote }}
  name: shipmight-api
  labels:
    {{- include "shipmight.commonLabels" . | nindent 4 }}
spec:
  selector:
    {{- include "shipmight.apiSelectorLabels" . | nindent 4 }}
  ports:
    - port: 3001
      protocol: TCP
