{{ if .Values.api.enabled }}
{{- /*
I do not understand why .Values.api.replicas is nil during install, when
it has a default value in values.yaml. So, check for type. ¯\_(ツ)_/¯
*/}}
{{ if kindIs "int64" .Values.api.replicas }}
{{ if ne .Values.api.replicas 1 }}
{{ fail "Greater than 1 .api.replicas is not currently supported" }}
{{ end }}
{{ end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace | quote }}
  name: shipmight-api
  labels:
    {{- include "shipmight.commonLabels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "shipmight.apiSelectorLabels" . | nindent 6 }}
  replicas: {{ .Values.api.replicas }}
  template:
    metadata:
      labels:
        {{- include "shipmight.apiSelectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: shipmight-api
      containers:
        - name: shipmight-api
          image: {{ include "shipmight.image" . }}
          {{ if .Values.image.pullPolicy }}
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          {{ end }}
          args: ['--api']
          ports:
            - containerPort: 3001
          resources: {{- toYaml .Values.api.resources | nindent 12 }}
          env:
            {{ include "shipmight.commonEnv" . | nindent 12 }}
            {{ include "shipmight.configEnv" . | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /v1/readyz
              port: 3001
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 5
      imagePullSecrets: {{- toYaml .Values.image.pullSecrets | nindent 8 }}
{{ end }}
