---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Release.Namespace | quote }}
  name: shipmight-api
  labels:
    {{- include "shipmight.commonLabels" . | nindent 4 }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: shipmight-api
  labels:
    {{- include "shipmight.commonLabels" . | nindent 4 }}
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- nonResourceURLs:
  - '*'
  verbs:
  - '*'

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: shipmight-api
  labels:
    {{- include "shipmight.commonLabels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: shipmight-api
  namespace: {{ .Release.Namespace | quote }}
roleRef:
  kind: ClusterRole
  name: shipmight-api
  apiGroup: rbac.authorization.k8s.io
