# TODO, maybe prefer a graphical installer instead? or both?
apiVersion: batch/v1
kind: Job
metadata:
  namespace: {{ .Release.Namespace | quote }}
  name: shipmight-install
  labels:
    {{- include "shipmight.commonLabels" . | nindent 4 }}
  annotations:
    helm.sh/hook: post-install,post-upgrade
spec:
  template:
    spec:
      serviceAccountName: shipmight-api
      restartPolicy: Never
      containers:
        - name: shipmight-install
          image: {{ include "shipmight.image" . }}
          {{ if .Values.image.pullPolicy }}
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          {{ end }}
          args: ['--install']
          resources: {{- toYaml .Values.install.resources | nindent 12 }}
          env:
            - name: NODE_ENV
              value: production
            - name: LOG
              value: "shipmight:"
            {{ include "shipmight.apiEnv" . | nindent 12 }}
      imagePullSecrets: {{- toYaml .Values.image.pullSecrets | nindent 8 }}

