---
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace | quote }}
  name: shipmight-secrets
  labels:
    {{- include "shipmight.commonLabels" . | nindent 4 }}
type: Opaque
data:
  AUTH_INITIAL_ADMIN_USER: {{ .Values.auth.initialAdminUser | b64enc | quote }}
  AUTH_INITIAL_ADMIN_PASS: {{ .Values.auth.initialAdminPass | b64enc | quote }}

  AUTH_JWT_SECRET: {{ .Values.auth.jwtSecret | required "JWT secret must be provided" | b64enc | quote }}
