---
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace | quote }}
  name: shipmight-secrets
  labels:
    {{- include "shipmight.commonLabels" . | nindent 4 }}
type: Opaque
{{ $previous := lookup "v1" "Secret" .Release.Namespace "shipmight-secrets" }}
data:
  AUTH_INITIAL_ADMIN_USER: {{ .Values.auth.initialAdminUser | b64enc | quote }}
  AUTH_INITIAL_ADMIN_PASS: {{ .Values.auth.initialAdminPass | b64enc | quote }}

  {{- if $previous }}
  AUTH_JWT_SECRET: {{ $previous.data.AUTH_JWT_SECRET | quote }}
  {{- else if .Values.auth.jwtSecret }}
  AUTH_JWT_SECRET: {{ .Values.auth.jwtSecret | b64enc | quote }}
  {{- else }}
  AUTH_JWT_SECRET: {{ randAlphaNum 40 | b64enc | quote }}
  {{- end }}
