---
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace | quote }}
  name: shipmight-secrets
  labels:
    {{- include "shipmight.commonLabels" . | nindent 4 }}
type: Opaque
{{ $previous := lookup "v1" "Secret" .Release.Namespace "shipmight-secrets" }}
data:
  INITIAL_ADMIN_USER: {{ .Values.config.initialAdminUser | b64enc | quote }}
  INITIAL_ADMIN_PASS: {{ .Values.config.initialAdminPass | b64enc | quote }}

  {{- if $previous }}
  JWT_SECRET: {{ $previous.data.JWT_SECRET | quote }}
  {{- else if .Values.config.jwtSecret }}
  JWT_SECRET: {{ .Values.config.jwtSecret | b64enc | quote }}
  {{- else }}
  JWT_SECRET: {{ randAlphaNum 40 | b64enc | quote }}
  {{- end }}
