{{ if .Values.ui.enabled }}
{{ if .Values.ui.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ .Release.Namespace | quote }}
  name: shipmight-ui
  labels:
    {{- include "shipmight.commonLabels" . | nindent 4 }}
    {{- range $key, $value := .Values.ui.ingress.extraLabels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  annotations:
    kubernetes.io/ingress.class: nginx
    {{- range $key, $value := .Values.ui.ingress.extraAnnotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  tls: {{ toYaml .Values.ui.ingress.tls | nindent 4 }}
  rules:
{{- range $i := until (int (max 1 (len .Values.ui.ingress.hosts))) }}
    - http:
        paths:
        - pathType: {{ $.Values.ui.ingress.pathType | quote }}
          {{ if gt (len $.Values.ui.ingress.hosts) 0 -}}
          host: {{ index $.Values.ui.ingress.hosts $i }}
          {{ end -}}
          path: {{ $.Values.ui.ingress.path | quote }}
          backend:
            service:
              name: shipmight-ui
              port:
                number: 3000
{{- end }}
{{ end }}
{{ end }}
