{{ if or .Values.ui.ingressPath .Values.ui.ingressHost }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ .Release.Namespace | quote }}
  name: shipmight-ui
  labels:
    {{- include "shipmight.commonLabels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        {{ if .Values.ui.ingressHost }}
        host: {{ .Values.ui.ingressHost | quote }}
        {{ end }}
        path: {{ printf "/%s" .Values.ui.ingressPath | quote }}
        backend:
          service:
            name: shipmight-ui
            port:
              number: 3000

{{ end }}
