# yaml-language-server: $schema=values.schema.json

image:
  registry: ghcr.io
  repository: shipmight/shipmight
  tag: "0.1.3"
  pullPolicy: IfNotPresent
  pullSecrets: []

auth:
  initialAdminUser: admin
  initialAdminPass: admin
  jwtSecret: ''

ui:
  ingressPath: shipmight
  ingressHost: ""
  # Deployment params
  replicas: 1
  resources:
    limits: { memory: "100Mi", cpu: "100m" }
    requests: { memory: "75Mi", cpu: "10m" }

domains:
  ingressClass: ingress-nginx

loki:
  endpoint: http://shipmight-loki:3100

acmeClusterIssuer:
  enabled: false
  adminEmailAddress: ""
  name: "Let’s Encrypt"
  server: "https://acme-v02.api.letsencrypt.org/directory"

api:
  readableUuids: true
  uuidLength: 5
  # Deployment params
  replicas: 1
  resources:
    limits: { memory: "100Mi", cpu: "100m" }
    requests: { memory: "75Mi", cpu: "10m" }

install:
  resources:
    limits: { memory: "100Mi", cpu: "100m" }
    requests: { memory: "75Mi", cpu: "10m" }
