image:
  registry: ghcr.io
  repository: shipmight/shipmight
  tag: "0.6.0"
  pullPolicy: IfNotPresent
  pullSecrets: []

config:
  initialAdminUser: admin
  initialAdminPass: admin
  jwtSecret: ""

  selfUpdateRepository: "https://shipmight.github.io/helm-charts"

  lokiEndpoint: ""

  readableUuids: true
  uuidLength: 5

ui:
  enabled: true

  replicas: 1

  resources:
    limits: { memory: "100Mi", cpu: "100m" }
    requests: { memory: "75Mi", cpu: "10m" }

  ingress:
    enabled: true
    extraAnnotations: {}
    extraLabels: {}

    path: /shipmight
    pathType: Prefix

    hosts: []

    tls: []

api:
  enabled: true

  replicas: 1

  resources:
    limits: { memory: "400Mi", cpu: "100m" }
    requests: { memory: "75Mi", cpu: "10m" }

install:
  enabled: true

  resources:
    limits: { memory: "100Mi", cpu: "100m" }
    requests: { memory: "75Mi", cpu: "10m" }
