apiVersion: v1
name: shipmight-stack
version: "0.1.3"
kubeVersion: ">= v1.21.4"

dependencies:
- repository: "https://shipmight.github.io/helm-charts"
# - repository: "file://../shipmight"
  name: shipmight
  version: "0.1.3"
  condition: shipmight.enabled
- repository: "https://kubernetes.github.io/ingress-nginx"
  name: ingress-nginx
  version: "^4.0.0"
  condition: ingress-nginx.enabled
- repository: "https://grafana.github.io/helm-charts"
  name: loki-stack
  version: "^2.5.0"
  condition: loki-stack.enabled
- repository: "https://charts.jetstack.io"
  name: cert-manager
  version: "^1.6.1"
  condition: cert-manager.enabled
- repository: "https://kubernetes-sigs.github.io/metrics-server"
  name: metrics-server
  version: "^3.7.0"
  condition: metrics-server.enabled
