shipmight:
  enabled: true

ingress-nginx:
  enabled: true
  controller:
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi

loki-stack:
  enabled: true
  # https://grafana.com/docs/loki/latest/configuration/examples/#almost-zero-dependencyyaml
  loki:
    config:
      auth_enabled: false
      server:
        http_listen_port: 3100
      distributor:
        ring:
          kvstore:
            store: memberlist
      ingester:
        lifecycler:
          ring:
            kvstore:
              store: memberlist
            replication_factor: 1
          final_sleep: 0s
        chunk_idle_period: 5m
        chunk_retain_period: 30s
      # memberlist:
      #   abort_if_cluster_join_fails: false
      #   bind_port: 7946
      #   join_members:
      #   - loki-gossip-ring.loki.svc.cluster.local:7946
      #   max_join_backoff: 1m
      #   max_join_retries: 10
      #   min_join_backoff: 1s
      schema_config:
        configs:
        - from: 2020-05-15
          store: boltdb-shipper
          object_store: s3
          schema: v11
          index:
            prefix: index_
            period: 24h
      storage_config:
        boltdb_shipper:
          active_index_directory: /data/loki/boltdb-shipper-active
          cache_location: /data/loki/boltdb-shipper-cache
          shared_store: s3
        aws:
          s3: s3://access_key:secret_access_key@custom_endpoint/bucket_name
          s3forcepathstyle: true
      limits_config:
        enforce_metric_name: false
        reject_old_samples: true
        reject_old_samples_max_age: 168h
      compactor:
        working_directory: /data/compactor
        shared_store: s3
        compaction_interval: 5m
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
  promtail:
    resources:
      limits:
        cpu: 200m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
  grafana:
    enabled: false
  prometheus:
    enabled: false
    alertmanager:
      persistentVolume:
        enabled: false
    server:
      persistentVolume:
        enabled: false

cert-manager:
  enabled: true
  installCRDs: true
  resources:
    limits:
      cpu: 10m
      memory: 64Mi
    requests:
      cpu: 10m
      memory: 64Mi
  webhook:
    resources:
      limits:
        cpu: 10m
        memory: 64Mi
      requests:
        cpu: 10m
        memory: 64Mi
  cainjector:
    resources:
      limits:
        cpu: 10m
        memory: 64Mi
      requests:
        cpu: 10m
        memory: 64Mi
  startupapicheck:
    resources:
      limits:
        cpu: 10m
        memory: 64Mi
      requests:
        cpu: 10m
        memory: 64Mi

metrics-server:
  enabled: true
  resources:
    limits:
      cpu: 10m
      memory: 64Mi
    requests:
      cpu: 10m
      memory: 64Mi
